# Generated by Django 5.0.2 on 2023-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='email@m.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='john', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(default='95'),
        ),
    ]
